---
# tasks file for firewallder
- name: Install firewalld
  yum: name=firewalld state=installed

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- name: Ensure configuration directories exist
  file:
    dest: "/etc/firewalld/{{ item }}"
    state: directory
    mode: 0750
  with_items:
    - zones
    - services

- name: Set the default zone
  command: "firewall-cmd --set-default-zone={{ default_zone }}"
  register: zone_result
  changed_when: "'ZONE_ALREADY_SET' not in zone_result.stdout"
  notify: reload firewalld

- name: Upload services
  copy:
    backup: yes
    src: "{{ item }}"
    dest: /etc/firewalld/services/
    owner: root
    group: root
    mode: 0640
  with_fileglob:
    - "{{ services_dir }}/*"
  notify: reload firewalld

- name: Upload zones
  copy:
    backup: yes
    src: "{{ item }}"
    dest: /etc/firewalld/zones/
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - "{{ zones_dir }}/*"
  notify: reload firewalld
